name: resident_tax
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "212121"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/images/ic_launcher.png"
